apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notion-blog.fullname" . }}-web
  labels:
    {{- include "notion-blog.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "notion-blog.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "notion-blog.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
        {{- with .Values.web.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: web
          image: {{ include "notion-blog.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- include "notion-blog.secretEnvFrom" . | nindent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.web.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
